---
title: "Residence time function and demo"
author: "Sasha D. Hafner"
output_format:
  gfm: default
---

# Overview
This is a simple R simulation of some arbitrary pool with discrete units flowing in and out.
It is meant to explore the concept of residence time.

# Packages

```{r}
library(data.table)
```

# The simulation function

```{r}

rtsim <- function(p0, r_in, r_out, dt, time) {

  # Create initial pool of particles
  p <- data.table(id = 1:p0, age = 0)

  # Number of time steps
  n <- time %/% dt

  # Loop through times
  for (t in 1:n) {

    # Add new particles (with new IDs)
    new_ids <- 1:(r_in * dt) + max(p$id)

    # Select random particles for removal
    old_ids <- sample(p$id, r_out * dt)

    # Update age of all particles in pool
    p$age <- p$age + dt

    # Update pool by removal and addition
    p <- rbind(p[!id %in% old_ids, ], data.table(id = new_ids, age = 0))
    
  }

  return(p)

}
```

# Application

1. Pool of 10,000 with flow rate in = flow rate out = 100.

```{r}
out <- rtsim(1E4, 100, 100, 1, 1000)
mean(out$age)
```

2. Increase flow.

```{r}
out <- rtsim(1E4, 200, 200, 1, 1000)
mean(out$age)
```

3. Decrease flow
   
```{r}
out <- rtsim(1E4, 10, 10, 1, 1000)
mean(out$age)
```

4. Flow in > flow out (pool size grows)

```{r}
out <- rtsim(1E4, 102, 100, 1, 1000)
mean(out$age)
nrow(out)
nrow(out) / 102
nrow(out) / 100
```

5. Flow out > flow in

```{r}
out <- rtsim(1E4, 100, 102, 1, 1000)
mean(out$age)
nrow(out) / 102
nrow(out) / 100
```





